services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pandoorac
      POSTGRES_USER: pandoorac
      POSTGRES_PASSWORD: ${RANDOM_DB_PASSWORD:-change-me}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pandoorac -d pandoorac"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${RANDOM_MINIO_SECRET:-change-me}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  app:
    build: .
    command: flask run --host=0.0.0.0 --port=5001
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      STORAGE_TYPE: minio
      DATABASE_URL: postgresql://pandoorac:${RANDOM_DB_PASSWORD:-change-me}@postgres:5432/pandoorac
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: ${RANDOM_MINIO_SECRET:-change-me}
      MINIO_BUCKET: pandoorac-local
      SECRET_KEY: ${RANDOM_SECRET_KEY:-dev-secret-key}
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - .:/app

volumes:
  pgdata:
  minio-data: 