"""add_google_maps_url_to_bag_data

Revision ID: 007_add_google_maps_url_to_bag_data
Revises: e5dc4e179728
Create Date: 2025-07-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007_add_google_maps_url_to_bag_data'
down_revision: Union[str, Sequence[str], None] = 'e5dc4e179728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag_data', sa.Column('google_maps_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag_data', 'google_maps_url')
    # ### end Alembic commands ###
