apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      {{- if .Values.nodePlacement.enabled }}
      {{- with .Values.nodePlacement.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodePlacement.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: app
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: DATABASE_URL
          value: postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.database }}
        - name: REDIS_URL
          value: redis://{{ .Release.Name }}-redis:6379
        - name: MINIO_ENDPOINT
          value: {{ .Release.Name }}-minio:9000
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.minio.accessKey }}
        - name: MINIO_SECRET_KEY
          value: {{ .Values.minio.secretKey }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }} 