apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app
type: Opaque
data:
  secret-key: {{ .Values.app.secretKey | b64enc }}
---
{{- if .Values.localStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-uploads
spec:
  accessModes:
    - ReadWriteMany  # Required for Azure File Share
  storageClassName: {{ .Values.localStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.localStorage.storageSize }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      {{- if .Values.nodePlacement.enabled }}
      {{- with .Values.nodePlacement.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodePlacement.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: app
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: POSTGRES_HOST
          value: {{ .Release.Name }}-postgresql
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgres-password
        - name: REDIS_URL
          value: redis://{{ .Release.Name }}-redis:6379
        - name: STORAGE_TYPE
          value: "local"  # Use local storage mounted to Azure File Share
        - name: UPLOAD_FOLDER
          value: {{ .Values.localStorage.mountPath | default "/app/uploads" }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-app
              key: secret-key
        - name: PREFERRED_URL_SCHEME
          value: https
        - name: SERVER_NAME
          value: {{ .Values.ingress.hostname }}
        {{- if .Values.localStorage.enabled }}
        volumeMounts:
        - name: uploads-storage
          mountPath: {{ .Values.localStorage.mountPath | default "/app/uploads" }}
        {{- end }}
      {{- if .Values.localStorage.enabled }}
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-uploads
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }} 